name: pytest

on:
  push:
    branches:
      - 'main'
      - $default-branch
  pull_request:
    branches:
      - 'main'
      - $default-branch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyscf
        pip install pytest
        pip install -e .
    - name: Test
      run: |
        export PYSCF_EXT_PATH=$(pwd):$PYSCF_EXT_PATH
        pytest -s pyscf/zora
        pytest -s pyscf/cvs
