name: coverage badge

on:
  push:
    branches:
      - 'main'
      - $default-branch

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov geometric
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          cmake g++ gfortran libopenblas-dev
        CMAKE_CONFIGURE_ARGS="-DBLA_VENDOR=OpenBLAS" \
          python -m pip install "git+https://github.com/pyscf/pyscf.git"
        python -m pip install -e .
    - name: Test and generate coverage
      run: |
        export PYSCF_EXT_PATH=$(pwd):$PYSCF_EXT_PATH
        python -s -m pytest --cov-report=json
    - name: Update Coverage Badge
      uses: we-cli/coverage-badge-action@8a0b6ee05f6dd0f294089cbe7a848452a2b43eef
